### ISSUE TITLE
Where all the drawable directory went ?

### ISSUE THREAD

**Issue by anonym2** [Dhaia/MoviesFollower#1]
I tried to build your app and all the drawable directory with the images , font you used are gone why ?

**Comment by Dhaia** [comment]
Hi, I just added the drawable and font files to the repository in my last commit.
Also, you need a Google API key and an IMDB API key.
You should put the MDB key in the ApiInterface.java in the network package.
And about the Google key, you should just make a string resource with the name YOUTUBE_API_KEY, and you'll be fine, the only place I use this key is in, adapters package -> TrailersRecyclerViewAdapter.java -> ImagesViewHolder class -> onClick method.
And if you want to just download the apk, here is a [**Direct link**](https://docs.google.com/uc?export=download&id=1Bh8s-RikywKXhPPdUzjHuw37VzQgDN9F)

**Comment by anonym2** [comment]
Hi thanks you for the folder , I hope the best for you , have a good day sir

**Comment by anonym2** [comment]
Hi Again just for saying that you're app helped me a lot for my Xml and the bad performance I had before ,  Im really thankfull , hope you the best Sir , Thanks you again
